[tool.poetry]
name = "etl-plano-de-saude"
version = "0.1.0"
description = ""
authors = ["Bruno"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "3.12.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
